### ISSUE TITLE
国内自用docker源推荐

### ISSUE THREAD

**Issue by LemonCANDY42** [xjxjin/scripts#1]
https://docker.chenby.cn
https://docker.awsl9527.cn
https://docker.1panel.live
https://dockerhub.icu
https://docker.anyhub.us.kg
https://dhub.kubesre.xyz
https://docker.m.daocloud.io
https://hub.rat.dev

**Comment by xjxjin** [comment]
感谢上报，排除已有，和经测试不可用，dhub.kubesre.xyz，这个源是可用的，我会添加进去
